name: Scheduled tests

on:
  push:
    branches:
      - cc/add_scheduled_tests
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

env:
  POETRY_VERSION: "1.7.1"

jobs:
  build:
    name: Python ${{ matrix.python-version }} - ${{ matrix.working-directory }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.11"
        working-directory:
          - "libs/ai-endpoints"
          - "libs/trt"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          working-directory: ${{ inputs.working-directory }}
          cache-key: scheduled

      - name: Install dependencies
        run: poetry install --with test,test_integration
        working-directory: ${{ inputs.working-directory }}

      - name: Run unit tests
        run: make tests
        working-directory: ${{ inputs.working-directory }}

      - name: Run integration tests
        env:
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
        run: make integration_tests
        working-directory: ${{ inputs.working-directory }}


      - name: Ensure the tests did not create any additional files
        working-directory: ${{ inputs.working-directory }}
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
